@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml


' LAYOUT_WITH_LEGEND()

title System Context diagram for Apple TV+

Person(customer, "Viewers", "A subscribtion account holder.")
System(apple_system, "Apple TV+", "System to continuously deliver video content via the Internet to the remote viewers.")

System_Ext(cdn, "Content Delivery Network", "Stores, manages and Distributes video content")
System_Ext(emailSystem, "Email System","An external exchange system for emails")
System_Ext(userDbms,"AWS + iCloud storage","Stores user profiles,credentials,preferences & viewing history")

Rel(customer, apple_system, "Searches and Views video content")
Rel(apple_system, cdn, "Fetches Video Content")
Rel(apple_system, emailSystem, "sends emails to")
Rel(apple_system,userDbms,"Access user related content")
@enduml